### ISSUE TITLE
hello,I have some question

### ISSUE THREAD

**Issue by iulmt** [master861/Decrypt9WIP#1]
1. How to test the 3ds system?
2. Would you tell me the 3ds ver4.4's Browser bug details?

PS: I am new and I just be interested.

**Comment by master-key-g** [comment]
Frist of all sorry my english is not very god i am are german second this is are repo from the orignale author d0k3.
This is only for 9.2 or for arm9loaderhax if both dosend match your 3ds new 3ds then this is not for you.
What your mean bye test?
And as say before if you dont have 9.2 or 10.6.X.XX your can not test anthing.
